service: have-a-cookie 

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-central-1

custom:
  webpackIncludeModules: true

functions:
  weigh:
    handler: handler._weigh
    events:
      - http:
          path: weigh
          method: post
          integration: lambda
