service: have-a-cookie 

plugins:
  - serverless-webpack

package:
  individually: true

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-central-1
  memorySize: 128

custom:
  webpackIncludeModules: true

functions:
  weight:
    handler: services/weight.handle
    events:
      - http:
          path: weights
          method: post
          integration: lambda
